title: Mehul Bagaria # The title of the blog
author: Mehul Bagaria # Your name 
email: mehulbagaria12@gmail.com # your email shown in the footer

url: "https://mehul-bagaria.github.io" # this is your site's root address.



description: > # this means to ignore newlines until "show_excerpts:" 
  Researcher, Indian Institute of Technology Roorkee
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://raw.githubusercontent.com/Mehul-Bagaria/Mehul-Bagaria.github.io/main/assets/images/mehul_github_io.jpeg" # avatar in about page
  about_you: Research scientist, Indian Institute of Technology Roorkee # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    #twitter: meenu1309
    github:  Mehul-Bagaria
    #scholar: hjyZvdgAAAAJ
    researchgate: Mehul-Bagaria
    # rss: RSS
    # dribbble: 
    # facebook: huangyz0918
    # flickr:   
    # instagram: 
    linkedin: mehul-bagaria-38ab5a119
    # pinterest: 
    # youtube: UCpj8oznjjLwVe5KHOGNrvnQ
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: iitrabhi/moving
plugins:
  - jekyll-feed



# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Text under the icons in footer
footer-text:
